amcl:
  ros__parameters:
    use_sim_time: false

    # 启用初始位姿设定，并在启动时自动设置
    set_initial_pose: true
    initial_pose: {x: 0.0, y: 0.0, z: 0.0, yaw: 0.0}

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"

    # 激光相关
    scan_topic: "/SMXFE/Scan"
    laser_model_type: "likelihood_field"
    laser_max_range: 30.0
    laser_min_range: 0.1
    laser_likelihood_max_dist: 2.0
    max_beams: 180

    # 运动模型 (Omni表明全向；若是差速轮建议用 nav2_amcl::DifferentialMotionModel)
    motion_model: "nav2_amcl::OmniMotionModel"
    odom_topic: "/SMXFE/Odom"

    # Odom 噪声参数
    odom_alpha1: 0.1
    odom_alpha2: 0.1
    odom_alpha3: 0.1
    odom_alpha4: 0.1

    # 其他AMCL常见参数
    max_particles: 5000
    min_particles: 500
    update_min_a: 0.1
    update_min_d: 0.05
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 1.1
    do_beamskip: false
    lambda_short: 0.1
    z_hit: 0.5
    z_max: 0.0
    z_rand: 0.5
    z_short: 0.0

map_server:
  ros__parameters:
    yaml_filename: "/home/smx/unitree_ros2_250221/Ros2Go2Estimator/local_file/map_new.yaml"

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: "/SMXFE/Odom"
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.1

planner_server:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.1
      stateful: True

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 1.0
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 1.0
      min_speed_theta: 0.0
      acc_lim_x: 1.0
      acc_lim_y: 0.0
      acc_lim_theta: 1.0
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.1
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.1
      short_circuit_trajectory_evaluation: True
      limit_vel_cmd_in_traj: False
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.5
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

# local_costmap:
#   local_costmap:
#     ros__parameters:
#       global_frame: odom
#       robot_base_frame: base_link

#       # 更新频率、发布频率、地图大小等
#       rolling_window: true
#       update_frequency: 10.0
#       publish_frequency: 5.0
#       width: 5
#       height: 5
#       resolution: 0.05
#       robot_radius: 0.5


#       # 关键：只启用 obstacle_layer 和 inflation_layer
#       plugins: ["obstacle_layer", "inflation_layer"]

#       obstacle_layer:
#         plugin: "nav2_costmap_2d::ObstacleLayer"

#         # 定义用于障碍物检测的传感器信息源
#         observation_sources: laser
#         laser:
#           topic: /SMXFE/Scan        # 激光扫描话题
#           sensor_frame: base_link   # 与激光雷达帧对齐或能转换到 base_link
#           data_type: LaserScan      # 如果是 LaserScan 类型
#           marking: true             # 根据激光标记障碍物
#           clearing: true            # 根据激光清除空闲区域
#           obstacle_range: 3.0       # 最大障碍物检测距离 (米)
#           raytrace_range: 4.0       # 最大射线跟踪距离 (米)
#           inf_is_valid: false       # 对无穷距离的激光束如何处理

#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         cost_scaling_factor: 5.0   # 影响障碍物周边渐进增值的系数
#         inflation_radius: 0.5       # 通胀半径 (米)

# global_costmap:
#   global_costmap:
#     ros__parameters:
#       global_frame: map
#       robot_base_frame: base_link
#       update_frequency: 10.0
#       publish_frequency: 5.0
#       width: 50
#       height: 50
#       resolution: 0.05
#       robot_radius: 0.4
#       observation_sources: laser
#       laser:
#         topic: /SMXFE/Scan          # 你的激光话题
#         sensor_frame: base_link     # 你的激光坐标系与base_link相同
#         data_type: LaserScan        # 如果是LaserScan类型
#         marking: true
#         clearing: true
#         obstacle_range: 3.0         # 探测障碍物最大距离
#         raytrace_range: 4.0         # 射线跟踪最大距离
#         inf_is_valid: false 
global_costmap:
  global_costmap:
    ros__parameters:
      footprint_padding: 0.03
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: false
      robot_radius: 0.5
      resolution: 0.05
      plugins: ["static_layer", "voxel_layer", "inflation_layer"] # "obstacle_layer",
      
      # obstacle_layer:
      #   plugin: "nav2_costmap_2d::ObstacleLayer"
      #   enabled: True
      #   observation_sources: scan
      #   footprint_clearing_enabled: true
      #   max_obstacle_height: 2.0
      #   combination_method: 1
      #   scan:
      #     topic: /SMXFE/Scan
      #     obstacle_max_range: 2.5
      #     obstacle_min_range: 0.0
      #     raytrace_max_range: 3.0
      #     raytrace_min_range: 0.0
      #     max_obstacle_height: 2.0
      #     min_obstacle_height: 0.0
      #     clearing: True
      #     marking: True
      #     data_type: "LaserScan"
      #     inf_is_valid: false
      

      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        unknown_threshold: 15
        mark_threshold: 0
        observation_sources: laser
        laser:
          topic: /SMXFE/Scan          # 你的激光话题
          sensor_frame: base_link     # 你的激光坐标系与base_link相同
          data_type: LaserScan        # 如果是LaserScan类型
          marking: true
          clearing: true
          obstacle_range: 3.0         # 探测障碍物最大距离
          raytrace_range: 4.0         # 射线跟踪最大距离
          inf_is_valid: false 

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.1

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.5
        cost_scaling_factor: 1.0
        inflate_unknown: false
        inflate_around_unknown: true
      always_send_full_costmap: True


local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: false
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05