amcl:
  ros__parameters:
    use_sim_time: false

    # AMCL对里程计噪声的估计参数
    alpha1: 0.01
    alpha2: 0.01
    alpha3: 0.01
    alpha4: 0.01
    alpha5: 0.01

    # 启用初始位姿设定，并在启动时自动设置
    set_initial_pose: true
    initial_pose: {x: 0.0, y: 0.0, z: 0.0, yaw: 0.0}

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"

    # 激光相关
    scan_topic: "/SMXFE/Scan"
    laser_model_type: "likelihood_field"
    laser_max_range: 30.0
    laser_min_range: 0.1
    laser_likelihood_max_dist: 2.0
    max_beams: 180

    # 运动模型 (Omni表明全向；若是差速轮建议用 nav2_amcl::DifferentialMotionModel)
    motion_model: "nav2_amcl::OmniMotionModel"
    odom_topic: "/SMXFE/Odom"

    # Odom 噪声参数 (可选，如果不识别则删除)
    odom_alpha1: 0.01
    odom_alpha2: 0.01
    odom_alpha3: 0.01
    odom_alpha4: 0.01

    # 其他AMCL常见参数
    max_particles: 5000
    min_particles: 500
    update_min_a: 0.1
    update_min_d: 0.05
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 1.1
    do_beamskip: false
    lambda_short: 0.1
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

map_server:
  ros__parameters:
    yaml_filename: "/home/smx/unitree_ros2_250221/Ros2Go2Estimator/local_file/map_new.yaml"

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: "/SMXFE/Odom"
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.1

planner_server:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      desired_linear_vel: 0.3
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.05

      # Critic 配置
      critics: ["PathAlign", "GoalAlign", "ObstacleFootprint"]
      PathAlign:
        scale: 32.0
      GoalAlign:
        scale: 24.0
      ObstacleFootprint:
        scale: 0.02

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 2.0
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.3
      observation_sources: laser
      laser:
        topic: /SMXFE/Scan          # 你的激光话题
        sensor_frame: base_link     # 你的激光坐标系与base_link相同
        data_type: LaserScan        # 如果是LaserScan类型
        marking: true
        clearing: true
        obstacle_range: 3.0         # 探测障碍物最大距离
        raytrace_range: 4.0         # 射线跟踪最大距离
        inf_is_valid: false 

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 1.0
      publish_frequency: 1.0
      width: 50
      height: 50
      resolution: 0.05
      robot_radius: 0.3
      observation_sources: laser
      laser:
        topic: /SMXFE/Scan          # 你的激光话题
        sensor_frame: base_link     # 你的激光坐标系与base_link相同
        data_type: LaserScan        # 如果是LaserScan类型
        marking: true
        clearing: true
        obstacle_range: 3.0         # 探测障碍物最大距离
        raytrace_range: 4.0         # 射线跟踪最大距离
        inf_is_valid: false 
