slam_toolbox:
  ros__parameters:

    # 重要的帧和话题名称
    map_frame: map
    odom_frame: odom
    base_frame: base_link_2D
    scan_topic: /SMX/Scan
    odom_topic: /SMX/Odom_2D
    odom_linear_covariance: 0.1    # 里程计线速度噪声
    odom_angular_covariance: 0.1   # 里程计角速度噪声
    use_odom_motion: true          # 是否使用里程计运动模型

    # TF发布频率 (Hz)
    transform_publish_period: 0.1
    transform_timeout: 0.1
    tf_message_filter_queue_size: 200

    # 激光扫描匹配相关参数
    max_laser_range: 30.0          # 激光雷达最大范围 (单位:米)
    min_laser_range: 0.20          # 激光雷达最小范围
    max_iterations: 500            # 匹配最大迭代次数
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05

    # 绘图
    map_update_interval: 0.1
    resolution: 0.25

    # 优化参数
    use_scan_matching: false
    use_scan_barycenter: false
    do_loop_closing: true
    position_covariance_scale: 1.0
    yaw_covariance_scale: 1.0
    loop_match_minimum_response_fine: 0.5
    distance_variance_penalty: 0.01
    angle_variance_penalty: 0.01    
    optimization_period: 0.5       # 优化间隔 (秒)
    loop_search_max_distance: 0.5  # 回环检测最大距离 (米)

    # CPU和内存控制
    throttle_scans: 1
    solver_plugin: solver_plugins::CeresSolver