slam_toolbox:
  ros__parameters:

    # 重要的帧和话题名称
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /SMXFE/Scan
    odom_topic: /SMXFE/Odom

    # TF发布频率 (Hz)
    transform_publish_period: 0.02
    transform_timeout: 0.1
    tf_message_filter_queue_size: 200

    # 激光扫描匹配相关参数
    max_laser_range: 30.0          # 激光雷达最大范围 (单位:米)
    min_laser_range: 0.1           # 激光雷达最小范围
    max_iterations: 20             # 匹配最大迭代次数
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1

    # 绘图
    map_update_interval: 2.0
    resolution: 0.05

    # 优化参数
    use_scan_matching: false
    use_scan_barycenter: false
    # position_covariance_scale: 1.0
    # yaw_covariance_scale: 1.0
    # do_loop_closing: false
    # loop_match_minimum_response_fine: 0.8
    # distance_variance_penalty: 1      
    # angle_variance_penalty: 1    
    optimization_period: 0.2       # 优化间隔 (秒)
    loop_search_max_distance: 5.0  # 回环检测最大距离 (米)

    # CPU和内存控制
    throttle_scans: 1
    solver_plugin: solver_plugins::CeresSolver
