function build_inekf_legged_mex()

this_dir  = fileparts(mfilename('fullpath'));
src_dir   = fullfile(this_dir, 'src');

% Correct the the path to your Eigen !!!!!!!!!!!!!!!!!
eigen_dir = '/home/smx/WorkSpace/Libraries/eigen-5.0.0';

srcs = { ...
    fullfile(this_dir, 'inekf_legged_core_mex.cpp'), ...
    fullfile(src_dir,  'InEKF.cpp'), ...
    fullfile(src_dir,  'RobotState.cpp'), ...
    fullfile(src_dir,  'LieGroup.cpp'), ...
    fullfile(src_dir,  'NoiseParams.cpp') ...
};

if ~isfolder(src_dir)
    error('build_inekf_legged_mex:Path', '未找到 src 目录：%s', src_dir);
end

if ~isfile(fullfile(this_dir, 'inekf_legged_core_mex.cpp'))
    error('build_inekf_legged_mex:Path', '未找到 MEX 源文件：%s', fullfile(this_dir, 'inekf_legged_core_mex.cpp'));
end

if ~isfolder(eigen_dir)
    error('build_inekf_legged_mex:Path', 'Eigen 目录不存在，请修改 eigen_dir：%s', eigen_dir);
end

if ispc
    mex('-R2018a', '-v', ...
        ['COMPFLAGS=$COMPFLAGS /std:c++17 /DINEKF_USE_MUTEX=0 /DNOMINMAX /D_USE_MATH_DEFINES'], ...
        ['-I' src_dir], ...
        ['-I' eigen_dir], ...
        srcs{:}, ...
        '-output', fullfile(this_dir, 'inekf_legged_core_mex'));
else
    mex('-R2018a', '-v', ...
        'CXXFLAGS=$CXXFLAGS -std=c++17 -DINEKF_USE_MUTEX=0 -DNOMINMAX -D_USE_MATH_DEFINES', ...
        ['-I' src_dir], ...
        ['-I' eigen_dir], ...
        srcs{:}, ...
        '-output', fullfile(this_dir, 'inekf_legged_core_mex'));
end
end